pacmanSHOW MACRO x,y
push ax
push bx
mov ax, 320
mov bx, y
mul bx
mov bx, ax
add bx, x
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 44
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 16
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
pop bx
pop ax
endm
