pacmanSHOW MACRO x,y
push ax
push bx
mov ax, 320
mov bx, y
mul bx
mov bx, ax
add bx, x
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 4096
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 11280
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 4096
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 4096
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 11280
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 11280
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 11280
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 11280
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 11280
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 4096
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 4096
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 11280
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 4096
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 11308
add bx, 2
mov es:[bx], WORD PTR 4140
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], WORD PTR 4112
add bx, 2
mov es:[bx], WORD PTR 16
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], WORD PTR 0
add bx, 2
mov es:[bx], BYTE PTR 0
inc bx
add bx, 303
pop bx
pop ax
endm
